version: '3'

services:
  email-sleuth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    command: ["serve", "--port", "8080"]
    restart: unless-stopped
